package com.crossover.trial.weather.model;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * A collected point, including some information about the range of collected values
 *
 * @author code test administrator
 */
//Getters, Setters, ToString and equals/hashcode autogenerated
@Getter
@Setter
@ToString
@EqualsAndHashCode
public class DataPoint implements DeepCloned
{
	private static final long serialVersionUID = 3549339775827934548L;

	private int first;
	private int second;
	private int third;
	private double mean;
	private int count;

	public DataPoint() 
	{
		first = 0;
		second = 0;
		third = 0;
		mean = 0.0;
		count = 0;		
	}

    protected DataPoint(int first, int second, int third, double mean, int count) 
    {
        this.first = first;
        this.second = second;
        this.third = third;
        this.mean = mean;
        this.count = count;
    }
    
    public static class Builder 
    {
    	private int first;
    	private int second;
    	private int third;
    	private double mean;
    	private int count;

        public Builder withFirst(int first) 
        {
            this.first = first;
            return this;
        }

        public Builder withSecond(int second) 
        {
        	this.second = second;
            return this;
        }

        public Builder withThird(int third) 
        {
        	this.third = third;
            return this;
        }

        public Builder withMean(double mean) 
        {
        	this.mean = mean;
            return this;
        }

        public Builder withCount(int count) 
        {
        	this.count = count;
            return this;
        }

        public DataPoint build() 
        {
            return new DataPoint(this.first, this.second, this.third, this.mean, this.count);
        }
    }
}
