package com.crossover.trial.weather.model;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * A collected point, including some information about the range of collected values
 *
 * @author code test administrator
 */
//Getters, Setters, ToString and equals/hashcode autogenerated
@Getter
@ToString
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor(force = true)
public class DataPoint implements DeepCloned
{
	private static final long serialVersionUID = 3549339775827934548L;

	private int first;
	private int second;
	private int third;
	private double mean;
	private int count;
    
    public static class DataPointBuilder 
    {
    	private int first;
    	private int second;
    	private int third;
    	private double mean;
    	private int count;

        public DataPointBuilder withFirst(int first) 
        {
            this.first = first;
            return this;
        }

        public DataPointBuilder withSecond(int second) 
        {
        	this.second = second;
            return this;
        }

        public DataPointBuilder withThird(int third) 
        {
        	this.third = third;
            return this;
        }

        public DataPointBuilder withMean(double mean) 
        {
        	this.mean = mean;
            return this;
        }

        public DataPointBuilder withCount(int count) 
        {
        	this.count = count;
            return this;
        }

        public DataPoint build() 
        {
            return new DataPoint(this.first, this.second, this.third, this.mean, this.count);
        }
    }
}
